name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download JUnit Console
        run: |
          mkdir -p lib
          curl -L -o lib/junit-platform-console-standalone-1.9.0.jar \
            https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.0/junit-platform-console-standalone-1.9.0.jar

      - name: Build project, generate docs, jar
        run: make all

      - name: Run tests
        run: make test
