name: Java CI with Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download JUnit Console
      run: |
        mkdir -p lib
        curl -L -o lib/junit-platform-console-standalone-1.9.0.jar \
        https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.0/junit-platform-console-standalone-1.9.0.jar

    - name: Compile and build everything
      run: make

    - name: Run tests
      run: make test

    - name: Run launch to verify app runs
      run: make launch

    - name: Clean build artifacts
      run: make clean
