name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make configure executable
      run: chmod +x configure

    - name: Run configure
      run: ./configure

    - name: Build project
      run: make

    - name: Run tests
      run: make check

    - name: Run distcheck
      run: make distcheck
