name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: https://sonarcloud.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'       # optionnel mais conseillé pour accélérer les builds
          java-home: ${{ env.JAVA_HOME }}

      - name: Check Java version
        run: java -version

      - name: Build with Maven
        run: mvn clean verify

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          args: >
            -Dsonar.projectKey=SteevenFht_competition
            -Dsonar.organization=SteevenFht
            -Dsonar.java.binaries=target/classes
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.junit.reportPaths=target/surefire-reports
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
