name: Java CI with Maven and SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build, test & coverage with Maven
        run: mvn clean verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=SteevenFht_competition
            -Dsonar.organization=SteevenFht
            -Dsonar.java.binaries=target/classes
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.junit.reportPaths=target/surefire-reports
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
